import type { ApartmentCardProps } from "../types/apartment";

function makePhotos(id: string, count: number): { url: string }[] {
  return Array.from({ length: count }, (_, i) => ({
    url: `https://picsum.photos/seed/${id}-${i}/800/500`,
  }));
}

export const MOCK_APARTMENTS: Omit<ApartmentCardProps, "isLiked" | "onLike">[] =
  [
    {
      id: "1",
      ownerId: "u1",
      title: "Затишна 2-к квартира, ЖК Семицвіт",
      description:
        "Простора квартира з ремонтом у тихому районі. Поряд парк, зупинки транспорту, магазини.",
      location: "вул. Шевченка",
      district: "Шевченківський",
      cost: 18500,
      rooms: 2,
      square: 54,
      floor: 4,
      floorInHouse: 12,
      photos: makePhotos("apt1", 4),
      ownerType: "Owner",
      rentType: "Default",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 0,
        elevator: 1,
        washer: 1,
        ac: 0,
        balcony: 1,
        pets: 0,
      },
    },
    {
      id: "2",
      ownerId: "u2",
      title: "Лофт апартаменти в центрі",
      description:
        "Стильні апартаменти у стилі лофт з панорамними вікнами. Ідеально для короткострокового проживання.",
      location: "просп. Свободи",
      district: "Галицький",
      cost: 22000,
      rooms: 1,
      square: 42,
      floor: 2,
      floorInHouse: 4,
      photos: makePhotos("apt2", 5),
      ownerType: "Rieltor",
      rentType: "Daily",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 1,
        elevator: 0,
        washer: 0,
        ac: 1,
        balcony: 0,
        pets: 1,
      },
    },
    {
      id: "3",
      ownerId: "u3",
      title: "Світла квартира, Сихів",
      description:
        "Затишна квартира на Сихові з новими меблями. Розвинена інфраструктура, школа поряд.",
      location: "просп. Червоної Калини",
      district: "Сихівський",
      cost: 14000,
      rooms: 2,
      square: 48,
      floor: 7,
      floorInHouse: 9,
      photos: makePhotos("apt3", 3),
      ownerType: "Owner",
      rentType: "Default",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 0,
        elevator: 1,
        washer: 1,
        ac: 0,
        balcony: 0,
        pets: 1,
      },
    },
    {
      id: "4",
      ownerId: "u4",
      title: "Пентхаус з терасою, Погулянка",
      description:
        "Розкішний пентхаус з великою терасою та видом на місто. Підземний паркінг, охорона.",
      location: "вул. Левицького",
      district: "Личаківський",
      cost: 35000,
      rooms: 3,
      square: 110,
      floor: 5,
      floorInHouse: 5,
      photos: makePhotos("apt4", 5),
      ownerType: "Rieltor",
      rentType: "Daily",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 1,
        elevator: 1,
        washer: 1,
        ac: 1,
        balcony: 1,
        pets: 0,
      },
    },
    {
      id: "5",
      ownerId: "u1",
      title: "Затишна квартира біля парку",
      description:
        "Однокімнатна квартира поряд з парком Франка. Тихе місце, зручне розташування.",
      location: "вул. Сахарова",
      district: "Франківський",
      cost: 16000,
      rooms: 1,
      square: 38,
      floor: 3,
      floorInHouse: 5,
      photos: makePhotos("apt5", 3),
      ownerType: "Owner",
      rentType: "Default",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 0,
        elevator: 0,
        washer: 0,
        ac: 0,
        balcony: 1,
        pets: 1,
      },
    },
    {
      id: "6",
      ownerId: "u2",
      title: "Новобудова ЖК Велика Британія",
      description:
        "Сучасна квартира в новобудові з якісним ремонтом. Закрита територія, відеоспостереження.",
      location: "вул. Пстрака",
      district: "Залізничний",
      cost: 25000,
      rooms: 2,
      square: 62,
      floor: 8,
      floorInHouse: 10,
      photos: makePhotos("apt6", 4),
      ownerType: "Rieltor",
      rentType: "Default",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 1,
        elevator: 1,
        washer: 1,
        ac: 1,
        balcony: 0,
        pets: 0,
      },
    },
    {
      id: "7",
      ownerId: "u3",
      title: "Студія на Сихові",
      description:
        "Компактна студія для 1-2 осіб. Все необхідне є, поряд зупинки та магазини.",
      location: "вул. Хуторівка",
      district: "Сихівський",
      cost: 11000,
      rooms: 1,
      square: 30,
      floor: 5,
      floorInHouse: 10,
      photos: makePhotos("apt7", 2),
      ownerType: "Owner",
      rentType: "Daily",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 0,
        elevator: 1,
        washer: 0,
        ac: 0,
        balcony: 0,
        pets: 0,
      },
    },
    {
      id: "8",
      ownerId: "u5",
      title: "3-кімнатна на Городоцькій",
      description:
        "Здається не просто трикімнатна квартира на Городоцькій а справжній портал у паралельний всесвіт де закони фізики і здорового глузду більше не діють коротше історія така що тут жила справжня орава циган їх було стільки що навіть таргани з’їхали в сусідній район через тисняву але свято тривало недовго бо в один чудовий день двері вирішили вийти з чату за допомогою СБУ хлопці залетіли так красиво що тепер у нас є ексклюзивна дизайнерська фішка а саме продірявлений диван через який можна дивитися в майбутнє або просто просунути ногу якщо вночі стане спекотно диван прошитий наскрізь чи то чергою чи то прикладом але виглядає як сучасне мистецтво в стилі мілітарі-шик сама квартира простора кімнати окремі що дуже зручно якщо ви хочете сховатися від спогадів про те що тут відбувалося раніше стіни пам’ятають і пісні під гітару і запах паленої гуми і як СБУшники пояснювали барону що податки треба платити навіть якщо ти торгуєш еліксиром вічної молодості залізничний район це взагалі топ локація бо шум трамваїв на Городоцькій це єдине що перебиває плач колишніх власників за втраченим золотим запасом якого до речі в квартирі вже немає не шукайте під лінолеумом там порожньо як у моєму гаманці після відпустки квартира ідеально підійде для сім’ї яка хоче гострих відчуттів або для людей які хочуть відчути себе героями кримінальної хроніки ціна всього 19 тисяч гривень за такий історичний об’єкт це майже задарма заїжджайте живіть тільки диван не зашивайте бо це вже пам’ятка архітектури місцевого значення і ніяких коней у під’їзді бо сусіди досі смикаються від кожного звуку підків короче дзвоніть дивіться і беріть з собою свячену воду про всяк випадок",
      location: "вул. Городоцька",
      district: "Залізничний",
      cost: 19000,
      rooms: 3,
      square: 80,
      floor: 2,
      floorInHouse: 9,
      photos: makePhotos("apt8", 4),
      ownerType: "Owner",
      rentType: "Default",
      details: {
        wifi: 0,
        furniture: 1,
        parking: 1,
        elevator: 0,
        washer: 1,
        ac: 0,
        balcony: 1,
        pets: 1,
      },
    },
    {
      id: "9",
      ownerId: "u4",
      title: "Квартира біля університету",
      description:
        "Зручне розташування для студентів і не тільки. Поряд університет, кафе, транспорт.",
      location: "вул. Університетська",
      district: "Галицький",
      cost: 20000,
      rooms: 2,
      square: 56,
      floor: 3,
      floorInHouse: 6,
      photos: makePhotos("apt9", 3),
      ownerType: "Rieltor",
      rentType: "Daily",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 0,
        elevator: 0,
        washer: 1,
        ac: 1,
        balcony: 0,
        pets: 1,
      },
    },
    {
      id: "10",
      ownerId: "u5",
      title: "Однокімнатна на Франка",
      description:
        "Невелика охайна квартира в тихому дворі. Після косметичного ремонту.",
      location: "вул. Івана Франка",
      district: "Франківський",
      cost: 13500,
      rooms: 1,
      square: 35,
      floor: 1,
      floorInHouse: 5,
      photos: makePhotos("apt10", 2),
      ownerType: "Owner",
      rentType: "Default",
      details: {
        wifi: 0,
        furniture: 1,
        parking: 0,
        elevator: 0,
        washer: 0,
        ac: 0,
        balcony: 0,
        pets: 0,
      },
    },
    {
      id: "11",
      ownerId: "u1",
      title: "Елітна квартира в центрі",
      description:
        "Представницька квартира в самому серці Львова. Авторський дизайн, преміум оздоблення.",
      location: "пл. Ринок",
      district: "Галицький",
      cost: 45000,
      rooms: 4,
      square: 120,
      floor: 3,
      floorInHouse: 4,
      photos: makePhotos("apt11", 5),
      ownerType: "Owner",
      rentType: "Daily",
      details: {
        wifi: 1,
        furniture: 1,
        parking: 1,
        elevator: 1,
        washer: 1,
        ac: 1,
        balcony: 1,
        pets: 0,
      },
    },
    {
      id: "12",
      ownerId: "u2",
      title: "Квартира на Личаківській",
      description:
        "Двокімнатна квартира в тихому будинку на Личаківській. Зручно добиратись до центру.",
      location: "вул. Личаківська",
      district: "Личаківський",
      cost: 17000,
      rooms: 2,
      square: 50,
      floor: 4,
      floorInHouse: 7,
      photos: makePhotos("apt12", 3),
      ownerType: "Rieltor",
      rentType: "Daily",
      details: {
        wifi: 1,
        furniture: 0,
        parking: 1,
        elevator: 1,
        washer: 1,
        ac: 0,
        balcony: 1,
        pets: 1,
      },
    },
  ];
