import type { ApartmentCardProps } from "../types/apartment";

export const MOCK_APARTMENTS: Omit<ApartmentCardProps, "isLiked" | "onLike">[] =
  [
    {
      id: "1",
      title: "Затишна 2-к квартира, ЖК Семицвіт",
      location: "вул. Шевченка",
      district: "Шевченківський",
      cost: 18500,
      rooms: 2,
      square: 54,
      floor: 4,
      floorInHouse: 12,
      photos: [{ url: "https://picsum.photos/seed/apt1/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "2",
      title: "Лофт апартаменти в центрі",
      location: "просп. Свободи",
      district: "Галицький",
      cost: 22000,
      rooms: 1,
      square: 42,
      floor: 2,
      floorInHouse: 4,
      photos: [{ url: "https://picsum.photos/seed/apt2/390/256" }],
      ownerType: "Rieltor",
    },
    {
      id: "3",
      title: "Світла квартира, Сихів",
      location: "просп. Червоної Калини",
      district: "Сихівський",
      cost: 14000,
      rooms: 2,
      square: 48,
      floor: 7,
      floorInHouse: 9,
      photos: [{ url: "https://picsum.photos/seed/apt3/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "4",
      title: "Пентхаус з терасою, Погулянка",
      location: "вул. Левицького",
      district: "Личаківський",
      cost: 35000,
      rooms: 3,
      square: 110,
      floor: 5,
      floorInHouse: 5,
      photos: [{ url: "https://picsum.photos/seed/apt4/390/256" }],
      ownerType: "Rieltor",
    },
    {
      id: "5",
      title: "Затишна квартира біля парку",
      location: "вул. Сахарова",
      district: "Франківський",
      cost: 16000,
      rooms: 1,
      square: 38,
      floor: 3,
      floorInHouse: 5,
      photos: [{ url: "https://picsum.photos/seed/apt5/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "6",
      title: "Новобудова ЖК Велика Британія",
      location: "вул. Пстрака",
      district: "Залізничний",
      cost: 25000,
      rooms: 2,
      square: 62,
      floor: 8,
      floorInHouse: 10,
      photos: [{ url: "https://picsum.photos/seed/apt6/390/256" }],
      ownerType: "Rieltor",
    },
    {
      id: "7",
      title: "Студія на Сихові",
      location: "вул. Хуторівка",
      district: "Сихівський",
      cost: 11000,
      rooms: 1,
      square: 30,
      floor: 5,
      floorInHouse: 10,
      photos: [{ url: "https://picsum.photos/seed/apt7/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "8",
      title: "3-кімнатна на Городоцькій",
      location: "вул. Городоцька",
      district: "Залізничний",
      cost: 19000,
      rooms: 3,
      square: 80,
      floor: 2,
      floorInHouse: 9,
      photos: [{ url: "https://picsum.photos/seed/apt8/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "9",
      title: "Квартира біля університету",
      location: "вул. Університетська",
      district: "Галицький",
      cost: 20000,
      rooms: 2,
      square: 56,
      floor: 3,
      floorInHouse: 6,
      photos: [{ url: "https://picsum.photos/seed/apt9/390/256" }],
      ownerType: "Rieltor",
    },
    {
      id: "10",
      title: "Однокімнатна на Франка",
      location: "вул. Івана Франка",
      district: "Франківський",
      cost: 13500,
      rooms: 1,
      square: 35,
      floor: 1,
      floorInHouse: 5,
      photos: [{ url: "https://picsum.photos/seed/apt10/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "11",
      title: "Елітна квартира в центрі",
      location: "пл. Ринок",
      district: "Галицький",
      cost: 45000,
      rooms: 4,
      square: 120,
      floor: 3,
      floorInHouse: 4,
      photos: [{ url: "https://picsum.photos/seed/apt11/390/256" }],
      ownerType: "Owner",
    },
    {
      id: "12",
      title: "Квартира на Личаківській",
      location: "вул. Личаківська",
      district: "Личаківський",
      cost: 17000,
      rooms: 2,
      square: 50,
      floor: 4,
      floorInHouse: 7,
      photos: [{ url: "https://picsum.photos/seed/apt12/390/256" }],
      ownerType: "Rieltor",
    },
  ];
